apiVersion: v1
kind: Pod
metadata:
  name: "{{ .Release.Name }}-smoke-test-pod"
  labels:
    app.kubernetes.io/name: "{{ .Release.Name }}"
  annotations:
    # This annotation allows `mpdev verify` to figure out that this pod is
    # the smoke test.
    marketplace.cloud.google.com/verification: test
spec:
  serviceAccountName: default
  containers:
    - name: smoke-test
      image: "{{ .Values.smokeTestImage }}"
      imagePullPolicy: Always
      env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: APP_INSTANCE_NAME
          value: "{{ .Release.Name }}"
  restartPolicy: Never
