apiVersion: v1
kind: Pod
metadata:
  name: smoke-test-pod
  annotations:
    # This annotation allows `mpdev verify` to figure out that this pod is
    # the smoke test.
    marketplace.cloud.google.com/verification: test
spec:
  # The "default" serviceaccount does not have any role attached by
  # default. So we just use the deployer's one for the purpose of these
  # smoke tests.
  serviceAccountName: "{{ .Release.Name }}-deployer-sa"
  containers:
    - name: smoke-test
      image: "{{ .Values.smokeTestImage }}"
      imagePullPolicy: Always
      env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: APP_INSTANCE_NAME
          value: "{{ .Release.Name }}"
  restartPolicy: Never
