apiVersion: v1
kind: Pod
metadata:
  name: "{{ .Release.Name }}-smoke-test-pod"
  labels:
    app.kubernetes.io/name: "{{ .Release.Name }}"
  annotations:
    marketplace.cloud.google.com/verification: test
spec:
  # Helm does not cope well with keys that contain a dash.
  # https://github.com/helm/helm/issues/2192#issuecomment-293739257
  serviceAccountName: "{{ index .Values "cert-manager" "serviceAccount" "name" }}"
  containers:
    - name: smoke-test
      image: "{{ .Values.smokeTestImage }}"
      imagePullPolicy: Always
      env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: APP_INSTANCE_NAME
          value: "{{ .Release.Name }}"
  restartPolicy: Never
