installCRDs: false

# The namespace for secrets in which cluster-scoped resources are found. (default "cert-manager")
secretsNamespace: cert-manager
serviceAccount:
  create: false
  name: google-cas-issuer
  annotations: {}

image:
  tag: 0.1.0
  repository: quay.io/jetstack/cert-manager-google-cas-issuer
  pullPolicy: IfNotPresent

replicaCount: 1

imagePullSecrets: {}
securityContext: {}
podSecurityContext: {}

nodeSelector: {}
affinity: {}
tolerations: {}

prometheus:
  # Enables the creation of the ClusterIP service.
  enabled: true

resources: {}
  # requests:
  #   cpu: 10m
  #   memory: 32Mi
