timeout: 1800s # 30m
substitutions:
  _CLUSTER_NAME: cluster-1
  _CLUSTER_LOCATION: europe-west2-b
  _APP_VERSION: 1.1.0-gcm.1
  _SOLUTION_NAME: jetstack-secure-for-cert-manager
  _CERT_MANAGER_VERSION: 1.1.0
  _CAS_ISSUER_VERSION: 0.1.0
  _PREFLIGHT_VERSION: 0.1.27
steps:
  - id: pull-preflight
    name: gcr.io/cloud-builders/docker
    args:
      - pull
      - quay.io/jetstack/preflight:v${_PREFLIGHT_VERSION}
    waitFor: ["-"]

  - id: tag-preflight
    name: gcr.io/cloud-builders/docker
    args:
      - tag
      - quay.io/jetstack/preflight:v${_PREFLIGHT_VERSION}
      - gcr.io/$PROJECT_ID/${_SOLUTION_NAME}/cert-manager-preflight:${_APP_VERSION}
    waitFor:
      - pull-preflight

  - id: push-preflight
    name: gcr.io/cloud-builders/docker
    args:
      - push
      - gcr.io/$PROJECT_ID/${_SOLUTION_NAME}/cert-manager-preflight:${_APP_VERSION}
    waitFor:
      - tag-preflight

  - id: pull-cas-issuer
    name: gcr.io/cloud-builders/docker
    args:
      - pull
      - quay.io/jetstack/cert-manager-google-cas-issuer:${_CAS_ISSUER_VERSION}
    waitFor: ["-"]

  - id: tag-cas-issuer
    name: gcr.io/cloud-builders/docker
    args:
      - tag
      - quay.io/jetstack/cert-manager-google-cas-issuer:${_CAS_ISSUER_VERSION}
      - gcr.io/$PROJECT_ID/${_SOLUTION_NAME}/cert-manager-google-cas-issuer:${_APP_VERSION}
    waitFor:
      - pull-cas-issuer

  - id: push-cas-issuer
    name: gcr.io/cloud-builders/docker
    args:
      - push
      - gcr.io/$PROJECT_ID/${_SOLUTION_NAME}/cert-manager-google-cas-issuer:${_APP_VERSION}
    waitFor:
      - tag-cas-issuer

  - id: pull-controller
    name: gcr.io/cloud-builders/docker
    args:
      - pull
      - quay.io/jetstack/cert-manager-controller:v${_CERT_MANAGER_VERSION}
    waitFor: ["-"]

  - id: pull-cainjector
    name: gcr.io/cloud-builders/docker
    args:
      - pull
      - quay.io/jetstack/cert-manager-cainjector:v${_CERT_MANAGER_VERSION}
    waitFor: ["-"]

  - id: pull-webhook
    name: gcr.io/cloud-builders/docker
    args:
      - pull
      - quay.io/jetstack/cert-manager-webhook:v${_CERT_MANAGER_VERSION}
    waitFor: ["-"]

  - id: tag-controller
    name: gcr.io/cloud-builders/docker
    args:
      - tag
      - quay.io/jetstack/cert-manager-controller:v${_CERT_MANAGER_VERSION}
      - gcr.io/$PROJECT_ID/${_SOLUTION_NAME}:${_APP_VERSION}
    waitFor:
      - pull-controller

  - id: tag-cainjector
    name: gcr.io/cloud-builders/docker
    args:
      - tag
      - quay.io/jetstack/cert-manager-cainjector:v${_CERT_MANAGER_VERSION}
      - gcr.io/$PROJECT_ID/${_SOLUTION_NAME}/cert-manager-cainjector:${_APP_VERSION}
    waitFor:
      - pull-cainjector

  - id: tag-webhook
    name: gcr.io/cloud-builders/docker
    args:
      - tag
      - quay.io/jetstack/cert-manager-webhook:v${_CERT_MANAGER_VERSION}
      - gcr.io/$PROJECT_ID/${_SOLUTION_NAME}/cert-manager-webhook:${_APP_VERSION}
    waitFor:
      - pull-webhook

  - id: push-controller
    name: gcr.io/cloud-builders/docker
    args:
      - push
      - gcr.io/$PROJECT_ID/${_SOLUTION_NAME}:${_APP_VERSION}
    waitFor:
      - tag-controller

  - id: push-cainjector
    name: gcr.io/cloud-builders/docker
    args:
      - push
      - gcr.io/$PROJECT_ID/${_SOLUTION_NAME}/cert-manager-cainjector:${_APP_VERSION}
    waitFor:
      - tag-cainjector

  - id: push-webhook
    name: gcr.io/cloud-builders/docker
    args:
      - push
      - gcr.io/$PROJECT_ID/${_SOLUTION_NAME}/cert-manager-webhook:${_APP_VERSION}

  - id: pull-ubbagent
    name: gcr.io/cloud-builders/docker
    args:
      - pull
      - gcr.io/cloud-marketplace-tools/metering/ubbagent:latest
    waitFor: ["-"]

  - id: tag-ubbagent
    name: gcr.io/cloud-builders/docker
    args:
      - tag
      - gcr.io/cloud-marketplace-tools/metering/ubbagent:latest
      - gcr.io/$PROJECT_ID/${_SOLUTION_NAME}/ubbagent:${_APP_VERSION}
    waitFor: ["pull-ubbagent"]

  - id: push-ubbagent
    name: gcr.io/cloud-builders/docker
    args:
      - push
      - gcr.io/$PROJECT_ID/${_SOLUTION_NAME}/ubbagent:${_APP_VERSION}
    waitFor: ["tag-ubbagent"]

  - id: build-smoke-test
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - "smoke-test.Dockerfile"
      - --tag
      - gcr.io/$PROJECT_ID/${_SOLUTION_NAME}/smoke-test:${_APP_VERSION}
      - "."
    waitFor: ["-"]

  - id: push-smoke-test
    name: gcr.io/cloud-builders/docker
    args:
      - push
      - gcr.io/$PROJECT_ID/${_SOLUTION_NAME}/smoke-test:${_APP_VERSION}
    waitFor:
      - build-smoke-test

  - id: set-data-test-schema-default-values
    name: gcr.io/cloud-marketplace-tools/k8s/dev
    entrypoint: bash
    args:
      - -exc
      - |
        cat data-test/schema.yaml | env -i \
          IMAGE=gcr.io/$PROJECT_ID/${_SOLUTION_NAME}/smoke-test:${_APP_VERSION} \
        envsubst | tee /dev/stderr > tmp && mv tmp data-test/schema.yaml
    waitFor:
      - "-"

  - id: build-deployer
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - --tag
      - gcr.io/$PROJECT_ID/${_SOLUTION_NAME}/deployer:${_APP_VERSION}
      - "."
    waitFor: ["set-data-test-schema-default-values"]

  - id: push-deployer
    name: gcr.io/cloud-builders/docker
    args:
      - push
      - gcr.io/$PROJECT_ID/${_SOLUTION_NAME}/deployer:${_APP_VERSION}
    waitFor:
      - build-deployer

  - id: gcloud-credentials
    name: gcr.io/cloud-builders/gcloud
    waitFor:
      - "-"
    entrypoint: bash
    args:
      - -exc
      - |
        gcloud container clusters get-credentials '${_CLUSTER_NAME}' --zone '${_CLUSTER_LOCATION}' --project '$PROJECT_ID'
        mkdir -p /workspace/.kube/
        cp -r $$HOME/.kube/ /workspace/
        mkdir -p /workspace/.config/gcloud/
        cp -r $$HOME/.config/gcloud/ /workspace/.config/

  - id: install-app-crds
    name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - -exc
      - kubectl apply -f "https://raw.githubusercontent.com/GoogleCloudPlatform/marketplace-k8s-app-tools/master/crd/app-crd.yaml"
    waitFor:
      - "gcloud-credentials"

  - id: install-cloud-marketplace-tools
    name: gcr.io/cloud-builders/docker
    args:
      - run
      - --volume
      - /workspace:/workspace
      - gcr.io/cloud-marketplace-tools/k8s/dev
      - sh
      - -c
      - |
        cat /scripts/dev > "/workspace/mpdev"
        chmod +x /workspace/mpdev
    waitFor: ["-"]

  - id: check-cloud-marketplace-tools
    name: gcr.io/cloud-marketplace-tools/k8s/dev
    env:
      - "KUBE_CONFIG=/workspace/.kube"
      - "GCLOUD_CONFIG=/workspace/.config/gcloud"
      # Use local Docker network named cloudbuild as described here:
      # https://cloud.google.com/cloud-build/docs/overview#build_configuration_and_build_steps
      - "EXTRA_DOCKER_PARAMS=--net cloudbuild"
    args:
      - ./mpdev
      - doctor
    waitFor:
      - gcloud-credentials
      - install-cloud-marketplace-tools
      - install-app-crds

  - id: logs-deployer
    name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - -exc
      - |
        while : ; do
          kubectl get ns -oname 2>/dev/null | grep apptest- && break
          sleep 10
        done
        ns=$(kubectl get ns -oname  | grep apptest- | cut -d/ -f2)

        while : ; do
          kubectl -n "$ns" get pods -oname 2>/dev/null | grep "apptest-.*-deployer" && break
          sleep 10
        done
        pod=$(kubectl -n "$ns" get pods -oname | grep "apptest-.*-deployer" | cut -d/ -f2)

        kubectl wait -n "$ns" --for=condition=ready --timeout=5m pod $pod
        kubectl logs -n "$ns" $pod -f --tail=-1
    waitFor:
      - check-cloud-marketplace-tools
      - push-deployer
      - push-controller
      - push-cainjector
      - push-webhook
      - push-cas-issuer
      - push-preflight
      - push-ubbagent

  - id: logs-smoke-test
    name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - -exc
      - |
        while : ; do
          kubectl get ns -oname 2>/dev/null | grep apptest- && break
          sleep 10
        done
        ns=$(kubectl get ns -oname  | grep apptest- | cut -d/ -f2)

        while : ; do
          kubectl -n "$ns" get pods -oname | grep "apptest-.*-smoke-test-pod" && break
          sleep 10
          done
        pod=$(kubectl -n "$ns" get pods -oname | grep "apptest-.*-smoke-test-pod" | cut -d/ -f2)

        kubectl wait -n "$ns" --for=condition=ready --timeout=5m pod $pod
        kubectl logs -n "$ns" $pod -f --tail=-1
    waitFor:
      - check-cloud-marketplace-tools
      - push-deployer
      - push-controller
      - push-cainjector
      - push-webhook
      - push-cas-issuer
      - push-preflight
      - push-ubbagent
      - push-smoke-test

  - id: verify
    name: gcr.io/cloud-marketplace-tools/k8s/dev
    env:
      - "KUBE_CONFIG=/workspace/.kube"
      - "GCLOUD_CONFIG=/workspace/.config/gcloud"
      # Use local Docker network named cloudbuild as described here:
      # https://cloud.google.com/cloud-build/docs/overview#build_configuration_and_build_steps
      - "EXTRA_DOCKER_PARAMS=--net cloudbuild"
    args:
      - ./mpdev
      - verify
      - --wait_timeout=99999999
      - --deployer=gcr.io/$PROJECT_ID/${_SOLUTION_NAME}/deployer:${_APP_VERSION}
    waitFor:
      - check-cloud-marketplace-tools
      - push-deployer
      - push-controller
      - push-cainjector
      - push-webhook
      - push-cas-issuer
      - push-preflight
      - push-ubbagent
      - push-smoke-test

  - id: publish
    name: gcr.io/cloud-marketplace-tools/k8s/dev
    env:
      - "KUBE_CONFIG=/workspace/.kube"
      - "GCLOUD_CONFIG=/workspace/.config/gcloud"
      - "EXTRA_DOCKER_PARAMS=--net cloudbuild"
    args:
      - ./mpdev
      - publish
      - --gcs_repo=gs://$PROJECT_ID
      - --deployer_image=gcr.io/$PROJECT_ID/${_SOLUTION_NAME}/deployer:${_APP_VERSION}
    waitFor:
      - verify

images:
  - gcr.io/$PROJECT_ID/${_SOLUTION_NAME}:${_APP_VERSION}
  - gcr.io/$PROJECT_ID/${_SOLUTION_NAME}/cert-manager-cainjector:${_APP_VERSION}
  - gcr.io/$PROJECT_ID/${_SOLUTION_NAME}/cert-manager-webhook:${_APP_VERSION}
  - gcr.io/$PROJECT_ID/${_SOLUTION_NAME}/cert-manager-google-cas-issuer:${_APP_VERSION}
  - gcr.io/$PROJECT_ID/${_SOLUTION_NAME}/cert-manager-preflight:${_APP_VERSION}
  - gcr.io/$PROJECT_ID/${_SOLUTION_NAME}/deployer:${_APP_VERSION}
  - gcr.io/$PROJECT_ID/${_SOLUTION_NAME}/ubbagent:${_APP_VERSION}
  - gcr.io/$PROJECT_ID/${_SOLUTION_NAME}/smoke-test:${_APP_VERSION}
