# https://github.com/GoogleCloudPlatform/marketplace-k8s-app-tools/blob/master/docs/schema.md
x-google-marketplace:
  schemaVersion: v2

  # MUST match the version of the Application custom resource object.
  # This is the same as the top level applicationApiVersion field in v1.
  applicationApiVersion: v1beta1

  # The release version is required in the schema and MUST match the
  # release tag on the the deployer.
  publishedVersion: "1.1.0"
  publishedVersionMetadata:
    releaseNote: >-
      Initial release.
    # releaseTypes list is optional.
    # "Security" should only be used if this is an important update to patch
    # an existing vulnerability, as such updates will display more prominently for users.
    releaseTypes:
      - Feature
      - BugFix
      - Security
    # If "recommended" is "true", users using older releases are encouraged
    # to update as soon as possible. This is useful if, for example, this release
    # fixes a critical issue.
    recommended: true

  # Image declaration is required here. Refer to the Images section below.
  images:
    cert-manager-controller:
      properties:
        cert-manager.image.repository:
          type: REPO_WITH_REGISTRY
        cert-manager.image.tag:
          type: TAG
    cert-manager-webhook:
      cert-manager.webhook.image.repository:
        type: REPO_WITH_REGISTRY
      cert-manager.webhook.image.tag:
        type: TAG
    cert-manager-cainjector:
      cert-manager.cainjector.image.repository:
        type: REPO_WITH_REGISTRY
      cert-manager.cainjector.image.tag:
        type: TAG

  # Other fields, like clusterConstraints, can be included here.

# The Properties and Required sections of v2 are structured the same as those of v1.
properties:
  name:
    type: string
    x-google-marketplace:
      type: NAME
  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE
  cert-manager.serviceAccount.name:
    type: string
    x-google-marketplace:
      type: SERVICE_ACCOUNT
      serviceAccount:
        description: >
          Monitors cert-manager custom-resources such as Certificate and
          Order, as well as
        roles:
          - type: Role
            rulesType: CUSTOM
            rules:
              - apiGroups: [""]
                resources: ["configmaps"]
                resourceNames: ["cert-manager-controller"]
                verbs: ["get", "update", "patch"]
              - apiGroups: [""]
                resources: ["configmaps"]
                verbs: ["create"]
          - type: ClusterRole
            rulesType: CUSTOM
            rules:
              - apiGroups: ["cert-manager.io"]
                resources: ["issuers", "issuers/status"]
                verbs: ["update"]
              - apiGroups: ["cert-manager.io"]
                resources: ["issuers"]
                verbs: ["get", "list", "watch"]
              - apiGroups: [""]
                resources: ["secrets"]
                verbs: ["get", "list", "watch", "create", "update", "delete"]
              - apiGroups: [""]
                resources: ["events"]
                verbs: ["create", "patch"]
  cert-manager.webhook.serviceAccount.name:
    type: string
    x-google-marketplace:
      type: SERVICE_ACCOUNT
      serviceAccount:
        description: >
          Creates and manages the self-signed CA that is served by the
          webhook and that the apiserver checks in order to authenticate
          the webhook.
        roles:
          - type: Role
            rulesType: CUSTOM
            rules:
              - apiGroups: [""]
                resources: ["secrets"]
                resourceNames:
                  # TODO: is there a way to parametrize this? In the helm
                  # chart we use {{ template "webhook.fullname" . }}-ca,
                  # but we don't seem to be able to do the same thing
                  - "cert-manager-webhook-ca"
                verbs: ["get", "list", "watch", "update"]

              # This single CREATE permission is for creating the
              # webhook-ca secret. The reason it is not with the above rule
              # is that it is not possible to grant CREATE permission on a
              # single resourceName.
              - apiGroups: [""]
                resources: ["secrets"]
                verbs: ["create"]
  cert-manager.cainjector.serviceAccount.name:
    type: string
    x-google-marketplace:
      type: SERVICE_ACCOUNT
      serviceAccount:
        description: >
          The cainjector component watches and populates the caBundle field
          of ValidatingWebhookConfiguration, MutatingWebhookConfiguration,
          and CustomResourceDefinition objects. These objects are used to
          configure how the Kubernetes API server connects to webhooks.
          This caBundle data is loaded by the Kubernetes API server and
          used to verify the serving certificates of webhook API servers.
        roles:
          - type: Role
            rulesType: CUSTOM
            rules:
              - apiGroups: [""]
                resources: ["configmaps"]
                resourceNames:
                  - cert-manager-cainjector-leader-election,
                  - cert-manager-cainjector-leader-election-core,
                verbs: ["get", "update", "patch"]
              - apiGroups: [""]
                resources: ["configmaps"]
                verbs: ["create"]
          - type: ClusterRole
            rulesType: CUSTOM
            rules:
              - apiGroups: ["cert-manager.io"]
                resources: ["certificates"]
                verbs: ["get", "list", "watch"]
              - apiGroups: [""]
                resources: ["secrets"]
                verbs: ["get", "list", "watch"]
              - apiGroups: [""]
                resources: ["events"]
                verbs: ["get", "create", "update", "patch"]
              - apiGroups: ["admissionregistration.k8s.io"]
                resources:
                  - "validatingwebhookconfigurations"
                  - "mutatingwebhookconfigurations"
                verbs: ["get", "list", "watch", "update"]
              - apiGroups: ["apiregistration.k8s.io"]
                resources: ["apiservices"]
                verbs: ["get", "list", "watch", "update"]
              - apiGroups: ["apiextensions.k8s.io"]
                resources: ["customresourcedefinitions"]
                verbs: ["get", "list", "watch", "update"]
              - apiGroups: ["auditregistration.k8s.io"]
                resources: ["auditsinks"]
                verbs: ["get", "list", "watch", "update"]

required:
  - name
  - namespace

deployerServiceAccount:
  description: >
    Creates the cert-manager CRDs and webhook configurations.
  roles:
    - type: ClusterRole
      rulesType: CUSTOM
      rules:
        - apiGroups: ["apiextensions.k8s.io"]
          resources: ["customresourcedefinitions"]
          verbs: ["*"]
        - apiGroups: ["admissionregistration.k8s.io"]
          resources:
            - "validatingwebhookconfigurations"
            - "mutatingwebhookconfigurations"
          verbs: ["*"]
