apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name | trunc 63 | trimSuffix "-" }}-ubbagent
  labels:
    helm.sh/chart: {{ .Chart.Name  }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/name: {{ .Release.Name | trunc 63 | trimSuffix "-" }}
    app.kubernetes.io/component: ubbagent
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name | trunc 63 | trimSuffix "-" }}
      app.kubernetes.io/component: ubbagent
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Release.Name | trunc 63 | trimSuffix "-" }}
        app.kubernetes.io/component: ubbagent
    spec:
      containers:
        - name: ubbagent
          image: "{{ .Values.ubbagent.image.repository }}:{{ .Values.ubbagent.image.tag }}"
          env:
            - name: AGENT_CONFIG_FILE
              value: "/etc/ubbagent/config.yaml"
            - name: AGENT_LOCAL_PORT
              value: "4567"
            - name: AGENT_ENCODED_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.ubbagent.reportingSecretName }}
                  key: reporting-key
            - name: AGENT_CONSUMER_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.ubbagent.reportingSecretName }}
                  key: consumer-id
          volumeMounts:
            - name: ubbagent-config
              mountPath: /etc/ubbagent
      volumes:
        - name: ubbagent-config
          configMap:
            name: ubbagent-config
