# The appVersion below are overridden by the `publishedVersion` that is set in
# `schema.yaml`. Changing the below version will not change the actual versions
# being pulled when the application is deployed from the Google Marketplace.
# Instead, you should update the image tags that are being re-tagged in
# `cloudbuild.yml`.
apiVersion: v2
engine: gotpl
name: jetstack-secure-gcm
version: 1.0.0
# These dependencies are not actually used by Helm because we have manually
# vendored the sub-charts.
# `helm dependency` commands will give incorrect results.
dependencies:
  - name: cert-manager
    version: v1.5.3
    appVersion: v1.5.3
    repository: ./charts/cert-manager
  - name: google-cas-issuer
    appVersion: 0.1.0
    repository: ./charts/google-cas-issuer
  - name: preflight
    version: 0.1.0
    appVersion: 0.1.27
    repository: ./charts/preflight
