# Note (1): why are serviceAccounts and RBAC disabled? While helm
# recommends that charts should create RBAC resources by default,
# Marketplace requires that charts must not create k8s service accounts or
# RBAC resources. See:
# https://github.com/GoogleCloudPlatform/marketplace-k8s-app-tools/blob/master/docs/building-deployer-helm.md

cert-manager:
  nameOverride: jetstack-secure-gcm
  fullnameOverride: cert-manager
  installCRDs: true
  global:
    rbac:
      create: false # see note (1)
  serviceAccount:
    create: false # see note (1)
  image:
    repository: marketplace.gcr.io/jetstack-public/jetstack-secure-for-cert-manager
    tag: 1.6.1-gcm.0

  acmesolver:
    image:
      repository: marketplace.gcr.io/jetstack-public/jetstack-secure-for-cert-manager/cert-manager-acmesolver
      tag: 1.6.1-gcm.0

  webhook:
    serviceAccount:
      create: false # see note (1)
    image:
      repository: marketplace.gcr.io/jetstack-public/jetstack-secure-for-cert-manager/cert-manager-webhook
      tag: 1.6.1-gcm.0

  cainjector:
    serviceAccount:
      create: false # see note (1)
    image:
      repository: marketplace.gcr.io/jetstack-public/jetstack-secure-for-cert-manager/cert-manager-cainjector
      tag: 1.6.1-gcm.0

  # In the context of click-to-deploy, the RBAC rules and service accounts
  # must be defined statically in the schema.yaml.
  # This is incompatible with the install-hook mechanism of startup API check
  # expects to be able to temporarily create and then delete RBAC and SA Disable
  # startup API check.
  startupapicheck:
    enabled: false

  ubbagent:
    # By default, the reportingSecretName will be set to
    #  ${helm-release}-license.
    #
    # reportingSecretName: chartname-license
    image:
      repository: marketplace.gcr.io/jetstack-public/jetstack-secure-for-cert-manager/ubbagent
      tag: 1.6.1-gcm.0

google-cas-issuer:
  nameOverride: jetstack-secure-gcm
  fullnameOverride: google-cas-issuer
  installCRDs: true
  serviceAccount:
    create: false # see note (1)
  image:
    repository: marketplace.gcr.io/jetstack-public/jetstack-secure-for-cert-manager/cert-manager-google-cas-issuer
    tag: 1.6.1-gcm.0

preflight:
  # By default, the preflight deployment is "disabled" by setting replicas=0.
  # See https://github.com/jetstack/jetstack-secure-gcm/issues/41
  replicaCount: 0
  nameOverride: jetstack-secure-gcm
  fullnameOverride: preflight
  serviceAccount:
    # name: foo
    create: false # see note (1)
  rbac:
    create: false # see note (1)
  image:
    repository: marketplace.gcr.io/jetstack-public/jetstack-secure-for-cert-manager/preflight
    tag: 1.6.1-gcm.0
