# Note (1): why are serviceAccounts and RBAC disabled? While helm
# recommends that charts should create RBAC resources by default,
# Marketplace requires that charts must not create k8s service accounts or
# RBAC resources. See:
# https://github.com/GoogleCloudPlatform/marketplace-k8s-app-tools/blob/master/docs/building-deployer-helm.md

cert-manager:
  nameOverride: jetstack-secure-gcm
  installCRDs: true
  global:
    rbac:
      create: false # see note (1)
  serviceAccount:
    create: false # see note (1)
  image:
    repository: marketplace.gcr.io/jetstack-public/jetstack-secure-for-cert-manager
    tag: 1.1.0-gcm.1

  acmesolver:
    image:
      repository: marketplace.gcr.io/jetstack-public/jetstack-secure-for-cert-manager/cert-manager-acmesolver
      tag: 1.1.0-gcm.1

  webhook:
    serviceAccount:
      create: false # see note (1)
    image:
      repository: marketplace.gcr.io/jetstack-public/jetstack-secure-for-cert-manager/cert-manager-webhook
      tag: 1.1.0-gcm.1

  cainjector:
    serviceAccount:
      create: false # see note (1)
    image:
      repository: marketplace.gcr.io/jetstack-public/jetstack-secure-for-cert-manager/cert-manager-cainjector
      tag: 1.1.0-gcm.1

google-cas-issuer:
  nameOverride: jetstack-secure-gcm
  installCRDs: true
  serviceAccount:
    create: false # see note (1)
  image:
    repository: marketplace.gcr.io/jetstack-public/jetstack-secure-for-cert-manager/cert-manager-google-cas-issuer
    tag: 1.1.0-gcm.1

preflight:
  nameOverride: jetstack-secure-gcm
  serviceAccount:
    # name: foo
    create: false # see note (1)
  rbac:
    create: false # see note (1)
  image:
    repository: marketplace.gcr.io/jetstack-public/jetstack-secure-for-cert-manager/preflight
    tag: 1.1.0-gcm.1

ubbagent:
  # By default, the reportingSecretName will be set to
  #  ${helm-release}-license.
  #
  # reportingSecretName: chartname-license
  image:
    repository: marketplace.gcr.io/jetstack-public/jetstack-secure-for-cert-manager/ubbagent
    tag: 1.1.0-gcm.1
