{{- if .Values.prometheus.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "google-cas-issuer.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "google-cas-issuer.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 9402
      targetPort: 9402
  selector:
    {{- include "google-cas-issuer.selectorLabels" . | nindent 4 }}
{{- end }}
