# This "smoke test" schema.yaml is an overlay on top of the main
# /schema.yaml. It is shipped with the deployer image (in /data-test) and
# is used by the command
#
#     mpdev verify
#
# To know more about the smoke tests:
# https://github.com/GoogleCloudPlatform/marketplace-k8s-app-tools/blob/c5899a92/docs/mpdev-references.md#smoke-test-an-application

properties:
  smokeTestImage:
    type: string
    # The variable IMAGE is envsubt'd in cloudbuild.yml. Note that due to
    # this envsubst, the tester image is hardcoded into the deployer image.
    # We wish we did not hardcode it, but we were not able to find a
    # workaround. Consequence: if the deployer image was created on the
    # "jetstack-public" project, then the "verify" step will only be able
    # to be run inside the "jetstack-public" project.
    default: $IMAGE
    x-google-property:
      type: IMAGE

  # We had to disable preflight so that `mpdev verify` would not fail. It
  # fails due to the fact that the preflight deployment never becomes
  # "ready" since the secret "agent-credentials" and the configmap
  # "agent-config" are absent from the cluster.
  preflight.replicaCount:
    type: integer
    default: 0
