replicaCount: 1

image:
  repository: quay.io/jetstack/preflight
  tag: v0.1.27

serviceAccount:
  create: false
  # name: ""
  annotations: {}

rbac:
  create: false

podAnnotations: {}

resources:
  limits:
    cpu: 200m
    memory: 200Mi
  requests:
    cpu: 200m
    memory: 200Mi
